[theme]
base = "light"
primaryColor = "#e63946"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#f1f3f4"
textColor = "#1d3557"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
